[ch02_strategic_design_principles]
== Strategic design principles
In this fast-paced digital world, Bitcoin evolves every day with the help of developers from all over the world. Some things, such as the five pillars of open blockchains by Andreas Antonopoulos, are still holding strong in Bitcoin. Those being: open, borderless, transparent, neutral, and censorship-resistant. Other aspects, such as privacy, speed, and transaction size, are continuously being improved. But something else that is changing for the good is the number of new people with different backgrounds entering the Bitcoin space for the first time. Teachers, marketers, journalists, politicians, designers, artists, lawyers, and many more jobs and skills have a role to play in the upcoming decades of Bitcoin. Companies and organizations would do well to stimulate and invest in the creation of more non-trivial job openings so that the community as a whole becomes more robust. Because with more diversity comes more expertise and new perspectives to help Bitcoin grow bigger and faster than it is growing right now. In the next decade, Bitcoin will need to shake off its reputation as nerd money and geek technology. Instead, it should become a universal, public service available and usable to anyone. What is needed is a broader approach. Not just focussing on Bitcoin as a technology but designing for the complete ecosystem, both digital and physical. A future where products, services, and the community are aligned and share the same beliefs and goals. And with that mindset, five strategic design principles for building Bitcoin will deserve extra attention in the next decades. 

=== Literacy
One of the biggest problems at the moment is Bitcoin's literacy. Most people today do not have enough information and understanding of the things that are related to Bitcoin. This kind of knowledge is essential because basic financial and technological literacy is becoming more mandatory in the digital and global times we live in today. The goal for improving Bitcoin literacy is to leave nobody behind when it comes to comprehending and using financial services through Bitcoin.

When strategic and service designers compose and visualize solutions, they look beyond a single product, service, or system. Also, compared to the design of products, strategic & service designers tend to look at a broader time horizon for change to be implemented. "If you give a man a fish, he eats for a day; If you teach a man to fish, he eats for a lifetime." This saying also applies to Bitcoin when designing sustainable solutions. The benefit of creating short-term solutions is that it takes relatively little effort and has a direct impact. The drawbacks are that these solutions often lack addressing the fundamental issues or target only a specific group of individuals. Designing long-term solutions are much harder and more challenging to tackle. The impact is often more significant because of the scale and depth of the knowledge shared. The drawback is that long-term solutions tend to take a longer time to implement.

One example of a long-term solution is to formalize Bitcoin fundamentals within the educational system. The long-term goal is to have teachers teach children about money and technology at schools. What teachers can do is help explain the concepts of cash and money creation. Interesting talks are; what gives money value, what is sound money, why we need financial inclusion, what the effects are of inflation, why sovereignty over cash, and personal data is essential. Mid-term goals have designers and developers create and improve products and services within the Bitcoin ecosystem that are easy to understand and use for everyone. They can start by avoiding technical jargon and applying relatable conceptual metaphors. When creating products that interact with Bitcoin, it is good to keep in mind that people are unique, as well as the context they use it. When explaining or onboarding people to Bitcoin, there is no "one-size-fits-all." People learn and approach things in different ways and at different paces. 
And when looking at short-term solutions, everyone who is a parent, friend, or social media content creator, can help spread information and knowledge about this technology. The best way is to take people along step-by-step and, if possible, one-to-one. Let people experience and learn to use Bitcoin by doing. Show the risks and responsibilities that come with self-custody. 

=== Usability
Design is about the realization of products and services with a specific purpose or use in mind. Usability is about avoiding and removing obstacles while interacting with these products and services. The goal is to create a seamless, smooth, and comfortable experience. These obstacles can be different things for different people in different situations. For some, it could be installing and using an application with too many steps and technical jargon. For others, simply finding a place to buy or spend bitcoin without repercussions can be challenging by itself. A strong focus on usability aids the adoption and retention of Bitcoin and the products which interact with the Bitcoin system. Ignoring usability will push Bitcoin further in the speculative and technical realms of magical internet money only used by geeks and nerds.

What is needed are more problem-solving people. People who use their minds, skills, and talents to help create better solutions. It can start with a little more empathy and interest in other people. We are all different with specific (dis)abilities and needs. Every little effort to help people understand, use things, save time or effort, will have a compounding impact. As an indication, there are more outstanding issues on code-repositories, than there are people to solve them. Some of those are as simple as translating them into native languages. 

When designing Bitcoin products and services, consider both macro and micro usability challenges. If you are a developer, tester, designer, researcher, architect, or any other digital professional, then try to find out causes that are hindering people using Bitcoin. If you are a policymaker, then create more regulatory clarity. If you are a teacher, include Bitcoin as a topic in your classes. And if you are good at art, then create something related to Bitcoin that makes people happy and think about it.

=== Autonomy
We seek control over all aspects of our life, the freedom to express ourselves and to do the things we want to do. We challenge ourselves, gain knowledge, and master skills to achieve new things, either alone or with others. Stimulating autonomy will lead to happiness and fulfillment. Take this away, by limiting choice or creating boundaries, and it will negatively affect people's emotions.
 
The challenges in this area are to make the Bitcoin system safe and easy to use for people so that they become more in control of their data and the tools they use. The strategy is to stimulate sovereignty safely while also allow and support options for personal creativity and expression. 

The open, borderless, and public nature of Bitcoin allows much of our behavior and decisions recorded on the blockchain. This level of transparency enhances our trust in the system and reveals any malicious behavior. However, Bitcoin is also neutral and censorship-resistant, and therefore it does not discriminate between good or bad transactions. Once someone or something connects the identity of a person to their blockchain transactions, these can still be used against them by those who do not share the same values. Instead, we should focus more on solutions in which the individual controls the conditions of sharing information with others. But also offer access to the required information and tools for people to become knowledgeable and competent.

=== Mastery
Over time, training, and gaining experience, people may achieve mastery in their craft. People spend countless amounts of time and effort to get better at things like exercise, playing music, create art, or devote time to other hobbies. The goal is to have fun and to feel good about it while doing it. By showing what is possible, others will try to achieve the same or more.

The mastery design principle focuses on techniques about motivation and stimulation. By positively getting people interested and excited as well as create and maintain desirable habits. Two key components are time and personal attention. Short-term solutions may not be enough to stay motivated. There needs to be a long term incentive to stay motivated. Creating human connections of like-minded people helps bring people together and share experiences.

Getting to the level of mastery is not easy. As with everything, it starts with knowing what to achieve and how to accomplish things. Gaining knowledge and skills can be achieved through sharing, open-sourcing information, and facilitating exploration. Examples of people showing their level of mastery help others inspiring to better envisioning them reaching the same level.

=== Charity
The design principle of charity is about offering our support to others who will benefit from this act of kindness. Some of the most valuable things we can give are our time and attention. For some, it can be the gift of practical knowledge, skills, or information. For others, it means showing that we care and listen to what somebody else has to say. The chances are that those who receive charity are likely to pass it on to others.

The approach is to emphasize the humanistic approach and stimulate environments where people can find and help each other. The challenge is to support different forms of charity. Open platforms are most suited for sharing knowledge, code, reviews, references, and so on. The more people can help and collaborate, the stronger and happier the community will become. Kind acts of charity are likely to attract more people to join and pitch in.

People have much to give. In social constructs, they are often rewarded either by increasing their social status within the community. Those who give are often more mentioned and referred to as experts. When offering things for free, people are more likely to try new things and engage more often. Giving back recognition to people who positively contribute to helping others should not be forgotten.
