[ch01_design_patterns]
== Design patterns
Every design solution is only as smart as its use. And the more people use it, the more valuable it becomes. Within the field of economics, this correlation is called the network effect. Design patterns are a way to describe best practices, explain good designs, and capture experience in a way that others can reuse them. This chapter dives deeper into some design patterns that make Bitcoin as a whole more valuable by optimizing the design for use. 

=== Aesthetic-usability effect
The first impression people have when visiting a website or application is crucial because this is a pivotal moment where they decide if they want to interact, or if they will continue to search for alternatives. The one thing people never have enough of is time and makes it a scarce asset to people's lives. First impressions play a crucial role in estimating if something is worth their time or not. 

The aesthetically-usability effect dictates that in the eye of the beholder, beautifully designed products are more pleasurable and easy to use than those that are not. There is an unwritten expectation that those who created the look and feel of a product equally thought and cared about the simplicity of using it. 

When applying the aesthetic-usability effect, it is essential to meet people's expectations. If the aesthetics are not up to date, people may distrust every other quality aspect of the product. And if the usability aspects are clucky, then people may never consider your product again based on false promises. Both need to be on par with the latest standards. For this reason, third party wallets are becoming increasingly more popular amongst beginning users than native wallets build by the same blockchain team. Developing an attractive looking front-end user interface with a smooth user experience is not the same as developing a stable and secure backend blockchain system.

=== Anchoring
Because Bitcoin is something very new and different entirely, a lot of people have or had difficulty understanding, explaining, using, or valuing it correctly at first glance. Anchoring is about connecting something people are not familiar with to something which they already know. The consequences of not correctly using anchors can be indecisiveness or making bad decisions.

People use anchors in situations where they try to seek agreements on price, quantity, or quality. For example, when a judge compares a situation to similar verdicts from the past. A good design includes helpful, unbiased, and meaningful references to help create a frame. When creating correct comparisons, be sure to include the right context and time. Keep in mind that some anchors work better for some people than others because of their situation. Some user research is required to find out what your target audience needs and why.

The one thing people still cannot agree upon is how to value Bitcoin in the past, present, and future. The anchors that people use are going into all directions from comparisons to worthless, digital collectibles to a scarce store of value like gold. 

=== Certainty effect
If offered a choice, people tend to choose for certainty over risk. This behavior is also known as the certainty effect. One of the traps that people fall for is that what people believe to be one-hundred percent true, is in reality, just a perceived certainty. This situation happens when the information people have is incomplete or incorrect.

Use the certainty effect pattern to avoid risk-taking situations such as creating a wallet, safely storing private keys or mnemonic phrases, and sending transactions to a recipient. In these situations, a wallet or service provider should be extra alert on taking safety measures to avoid mistakes. A good practice is to provide clear and understandable insights about the actual risks and benefits of specific actions to prevent people from being misled or uninformed. The more specific, complete, and neutral the information is, the more helpful it will be.

A great example of the certainty effect in practice is the decision for people to keep their assets under the supervision and control of custodians, such as cryptocurrency exchanges or financial institutions. The logic of this being that these custodians have better security measures in place, and offer consumer protection for loss of funds compared individually taking safety measures. The perception is that there is a bigger chance that the majority of people lack the knowledge of safely securing their assets and fear losing it permanently when mistakes occur. As long as people see any perceived risk in using Bitcoin, they will tend to avoid it and choose what they believe is the safest option. That is why the next generation solutions should also consider debasing risk. One approach to do this could mean restricting risky functionality for certain people, or until they are familiar with the risks. Only when they feel confident, can they choose to opt-in for more advanced features. However, the best approach will always be to eliminate and prevent all human errors before they can occur, for example, by including checks and validations as well as easy-to-understand steps tailor-made for different user needs.

=== Challenges
Research studies confirm that there is a relation between happiness and tackling problems. If things are too easy, and their brains are getting into an automated state of mind, people quickly become bored, and their brain dumbs down. But when things are too hard, people may become overwhelmed and frustrated. In both situations, accidents and human mistakes can happen. Between these two extremes lies a sweet spot to get people engaged and excited. It is this challenge that motivates people and influences behavior. Where to find this sweet spot depends on the challenge, people's skills, and their knowledge of the problem. 

The best way of finding out what kinds of challenges are needed is by doing research, observations, and gathering feedback. These activities will give insights into the competence levels from beginner to advanced. Products and services should be flexible enough to support all kinds of challenges to keep people happy during their interactions. Increasing difficulty over time keeps people engaged and motivated. But using this pattern should not be a goal by itself, but a means to an end.
In some cases, a challenge may not be enough to keep people motivated. This lack of motive often happens when people need to do things instead of finding value or fun in doing it. In these situations, there is often the expectation of a reward or follow-up on this achievement after completion. 

When taking into account the design principles, using challenges to learn can be a great way to achieve autonomy and mastery. When incentivizing people to learn about Bitcoin, to send and receive bitcoins, or to set up Bitcoin and Lightning nodes, more people would be willing to take the effort and spend their time to gain this knowledge and skills. "Stacking Sats" is a term often used for collecting small amounts of satoshis by performing small tasks such as liking and subscribing to social media. But there are also different kinds of rewards such as access to new features or gaining insights into personal progress to keep people engaged and motivated.

=== Consistency
Consistency plays a big part in the design of things. When designed correctly, people are more effective and efficient when taking up new tasks that are similar to those who are consistent with previous experiences. Like usability, consistency is not just limited to a single brand but works best when things work the same across multiple products and services. Driving consistency in an open-source ecosystem can be challenging due to the lack of cross-product comparisons and reviews. But eventually, the end-users will have their say on what works well and whatnot. The benefit of consistency is that it stimulates predictive behavior, and build on long-term trust. 

One area which benefits from consistency is standardization. By creating a certain open standard, it allows different protocols to share information and create seamless user experiences. In most cases, this is a win-win situation, especially for the end-user. The way to avoid inconsistency is simply to stick to default or standard, which is already used by others. Deviating from this standard is possible but only for good reasons such as a change of context, like adding more details and options for experts, who are already more familiar with the nuances.

One example of inconsistency is found in naming and terminology, using alternative descriptions for the same thing. Take the concept of a seed phrase, which consists of a list of words to recover a wallet containing private keys, public keys, and addresses. This concept is commonly first introduced when creating a new one for the first time. But depending on the creators of the wallet, this list of words used for recovery is called many things, like seed phrase, recovery phrase, back-up seed phrase, mnemonic phrases, or even more technically a BIP39 wordlist.

=== Confirmation bias
When people find information that is already in line with their beliefs, they are more likely to assume this as the truth. Although people love to hear about the things that they already believe, it can be refreshing to hear about alternatives that may approach things differently.

Using this pattern can be both helpful or dangerous, depending on how you use it. Within search engines, news, social media, and marketing use this pattern to explicitly find and snow similar results based on people's interests. Often this is referred to as "search optimization." The drawback is that there is often more than one side to a story. When people see with the same kind of information, it may implicitly create a bias towards a particular topic, losing its neutrality.

When people are (emotionally, financially, etc.) invested in a specific blockchain initiative such as Bitcoin, they often seek like-minded people on social media. Many great things can blossom from the interaction between people sharing knowledge and skills. But when this energy is applied negatively, open en free discussions may soon turn toxic. The best way to address this is by people from within the same community.

=== Control
As people, we desire autonomy and seek out situations where we can exert influence or control over something. Loss of control can make us feel dependent. But giving a choice to others is only desirable if they know that they can wield it properly. Having control over something is not always a guarantee that it will benefit people, and may put them into a worse situation. 

When making people autonomous, keep in mind that the level of user control should be related to the proficiency and experience of the user. If they seek to be more independent, help them gain the required knowledge and expertise. 

Bitcoin is about giving financial control back to the individual. By doing so, every person will have the autonomy and freedom to exercise their level of control as they see fit. The decentralized network enables direct payments between two or more parties without intermediaries. Decentralization of power is one of the key reasons why people feel free to operate within the network. As long as no individual or group can control the whole network, trust in the system remains intact. But one of the problems is that not everyone utilizes this possibility. They may have the opportunity but fear the responsibility. What could help is creating safe environments where people can try out and experiment, or watch others do it first, will help people become more confident and also take back control.

=== Curiosity
As humans, we are natural explorers. Our innate curiosity brings us to places we have never seen and do things we have never done. When teased with a small bit of interesting information, people will want to know more. 

A big part of curiosity is the incentive or expectation of a reward afterward that encourages particular behavior. It helps motivate people to explore and move them out of their comfort zone. Another approach is to show examples of people like them who have already achieved something through exploration. But sometimes, the mystery of attaining something unknown can become a part of someone's motivation.

One of the biggest challenges for Bitcoin is education. And using curiosity for this can be a great match. Small nuggets of information, could set people to think and motivate them te become eager to know more. Highlight positive facts about Bitcoin and let people discover how these facts came true.

=== Delayed gratification
Over time, technology helped humans to speed things up by making processes and production faster by automation and digitization. Ever since the clock was widely adopted, people became more aware of time and living by the clock. Now more then ever, every moment is getting more valuable and precious. Nowadays, there is the expectation that things happen instantly or give instant satisfaction. Delayed gratification is about resisting a smaller but more immediate reward now to receive a more substantial or more enduring compensation later. Someone with a high time preference is focused substantially on their needs in the present and the immediate future, while someone with low time preference places more emphasis on their well-being in the distant future.

From a design perspective, delayed gratification is about positively influencing people's behavior over time. There are several strategies to help people increase or decrease their ability to delay gratification. A short-term approach is a distraction to allow them to 'forget' or 'ignore' their impulses to take action. But once they stop being distracted, their minds wander off and turn back to an instant gratification mode. A better approach is to reward people over time with something they may value, such as motivational speeches, recognition for their accomplishments, or unlocking new possibilities. Something else that helps people delay gratification is having a focus on a particular goal in mind. When combined with compounding or increased value of the rewards, the longer they may resist their temptations. But the most drastic and practical approach is to take away people's control over their urges. In this case, the ability to seek satisfaction is removed or forcefully delayed in time. It may seem like an anti-pattern of usability, but adding obstacles may help people resist their bad behaviors. 

A person's ability to delay gratification relates to other similar skills such as patience, impulse control, self-control, and willpower, all of which are involved in self-regulation. Within the Bitcoin communities, those who can delay gratification are more commonly known as Hodler's (ability to hold and not sell their bitcoins). Their mindset is more focused on the long-term bitcoin value, rather than short-term bitcoin price. When designing for delayed gratifications, it is good to keep in mind your audience and which approach works the best for them. In general, younger people have a shorter focus span, seek more instant gratification than older adults. But also people with more experience over time are trained to delay their gratification and not to give in easily. Willpower is like a muscle that you can train over time. And those who cannot resist the urge may benefit from Bitcoin's Timelocks in wallets. This way, people are not able to spend their bitcoins until a precise future moment in time.

=== Delighters
New and unexpected discoveries arouse our brains. We remember and respond favorably to small surprising and playful pleasures. The combination of something unintended and pleasurable makes it very powerful. We like gifts, but when everyone else is receiving the same, it lessens the experience. And those who do not receive anything under the same circumstances will get disappointed. Excluding delighters may not negatively impact the experience because they always happen unexpectedly. But brands that want to distinguish themselves from the rest do use them to bring that extra bit of happiness.

One approach for including delighters is through the use of variable rewards that seem scarce and unpredictable. Especially games uses this in the form of 'drop crates' or 'loot boxes.' The content is often unknown until a player opens it. But a delighter may also come in the form of a compliment or an exclusive invite to some event.

Delighters are perhaps the opposite of Bitcoin. The Bitcoin platform is predictable and works according to rules. Delighters work best when not expected and happen at random. Both are positive and work well together but in different ways. This fact does not imply that those who design products and services on top of Bitcoin should not use this. Quite the opposite. There are infinite opportunities for applying delighters and show that using Bitcoin can be fun and exciting.

=== Dunning-Kruger effect
When unskilled people overestimate their competence and performance, that is called the Dunning-Kruger effect. The Dunning-Kruger effect showed that this intrinsic versus extrinsic gap could lead to dangerous situations such as causing harm or losing funds. 

Security is not just a matter of math and computer science, but also addressing behavioral aspects and education. Instead, it is better to understand people's thoughts and create new or better solutions for their needs. As for safely backing up seed phrases, there is increasing adoption of Shamir's Secret Sharing to address these practical needs.

One of the most common examples is chopping up a seed phrase, thinking that it will enhance security. When it comes to valuable assets, people tend to take protective measures to secure them from theft or damage. Read more about this on the topic of loss aversion for more information. Unfortunately, sometimes the wrong types of measures are being used due to lack of understanding. The result of this could lead to the exact opposite and total loss of the assets people willing to protect. One such example is how some people try to add extra layers of protection to store their seed phrase. The seed phrase, containing a list of back-up words for recovery, is often stored offline and put away safely. Yet some people are afraid of this list being stolen or damaged when put into one place. A common bad practice is to cut this list of words into multiple parts and store them in different locations. But what these people do not realize is that by cutting them up, they increase the chance of losing or destroying a part of this list. And when one part is missing, the incomplete seed phrase cannot be used for recovery. 

=== Duration effects
Even though time itself can be objectively measured, the perception of time is subjective. Something long may seem quick, and something brief may seem to take forever. The duration effect pattern allows designers to play with perceptions of time so that the recollection of a situation tends to become more positive. 

Theme parks have mastered the arts of this in each step of an attraction. By entertaining and keeping customers moving in long waiting lines, they take away their focus on time and waiting. Whereas the opposite is happening for the attraction itself that is short, but very intense, making it appear a bit longer. 

When designing for time-consuming experiences, be sure to include indicators in every part of the user-journey process. Allow people to have control over each step, by either opt-out, finish at a later moment, or speed things up by skipping steps. One such example is sending and receiving transactions. Some may take minutes, where others may take hours to verify. Although Bitcoin has it's own inner working, how we present and use this information may differ from one solution to the next. When designing for on-chain bitcoin transactions, be informative on how much time some steps may take. When receiving bitcoin transactions, be clear and transparent when and what options people may have to speed things up. Advanced users may understand the concept of transaction fees and network validations. But people new to the technology are more familiar with existing progress bars and status indicators such as; "processing" and "received." When in doubt, pick the option that works best for most people.

=== Error-handling
When overlooking or underdeveloping proper error-handling, you leave people hanging with little help to get back on the right path. A good error-handling is a combination of multiple good practices such as error-prevention, constraints, confirmation, formulation, forgiveness, and undo-actions. By including some kind of forgiveness, helps people avoid errors and protect them from harm when they do occur. Assets put onto the blockchain often hold value, and nobody wants to lose value. Solutions that prevent people from making mistakes will keep their customers. Those who don’t will search for alternatives.

When designing for proper error-handling, consider the following chronological order. First, design solutions to prevent mistakes, then include warnings for potential problems, followed by options to reverse mistakes when they occur, and when all else fails, add a safety net. 

Especially in the Bitcoin system, actions are often permanent. A good practice is to prevent errors by requiring confirmation or verification before performing impactful operations. Triggers are small nudges placed on our regular paths to remind and motivate us to take action. But be careful not to overdo this technique because else they will be ignored or blindly clicked upon after too many repetitions. Another method that can be helpful is adding constraints to the design of products. Adding constraints might help prevent destructive actions if users have not proven to have mastered the knowledge or skills needed to perform specific actions successfully. Related to this are two other design patterns; control and mastery. These explain that the level of user control should be related to the proficiency and experience of the user. But constraints may also be useful to restrict certain users from doing actions that are not approved by other users — for example, one child claiming the entire inheritance without approval from the other spouse. A multi-signature contract is an example of adding rules and constraints. There is another guideline that often functions as a last resort; the confirmation prompt. This dialog acts as the final step before setting things into motion. Although many people find this additional step annoying, for destructive or irreversible actions such as sending a transaction to an immutable ledger, it may act as a last resort. Be clear about what is going to happen and always set the cancel option as the default operation. But even after all preventative measures, people unintentionally make mistakes. By design, Bitcoin is not very forgiving, and most actions are final, making it difficult to support “rollback” or “undo” effects. But with a bit of exploration and imagination, there are exceptions such as the mempool. The mempool is the place where miners can pick and choose what to include (or not) in the next block. Once added inside the Bitcoin blockchain, after about six commits (or 1 hour), changes become near impossible. But when a transaction is still inside the mempool, there is an option to overwrite it with some alterations. Currently, it is up to software wallet providers to include this as an advanced option or not. But what should be included are clear (error) messages. A good (error) message contains the following elements; a short description of what happened, followed by why it happened, and, if possible, a suggestion on some follow-up action. Avoid technical jargon and write the message in an easy to understand human language. Only computers understand error-codes, so avoid including these in the prompt.

=== Education & learning
Although more and more people know about Bitcoin, only a tiny percentage understands it well. Bitcoin is many things depending on who you ask it, for they may need and use it for different reasons. But whatever their interest in Bitcoin, practical education and learning is required when using this technology. 

Understanding what Bitcoin is will help people try it out. Using it without understanding it, may result in losing funds. Bitcoin products can adopt positive mimicry & sequencing: learn by modeling other’s behaviors. YouTube tutorials. Instructions. Break it down into smaller tasks (setting up a wallet).

At the moment, education and learning are still a bit of an afterthought. The past has shown that most occurring security breach for people losing bitcoins are not 51% attacks, but simple avoidable human errors and mistakes. In most cases, people should have some basic or even advanced understanding. But who teaches them? Ideally, schools will be teaching the basics of Bitcoin. And hopefully, parents also educate their children about money and cryptocurrencies at home. And finally, exchanges and wallet providers should be offering the basics already. Unfortunately, not everybody is interested in macro-level economics, the creation of money, decentralized networks, privacy, or financial sovereignty. Like politics, these things can be too conceptual and too far off people’s daily life, or so they believe. But the fact is that people could lose stuff. In Bitcoin, things are irreversible thanks to the immutable blockchain. In Bitcoin, people become their banks, along with all of the responsibilities of a bank. That is why if people want or need to use Bitcoin, they must know what they are doing and the best way of doing it. As for the companies who wish to act as an interface between people and the Bitcoin network, this can be an excellent opportunity to help onboard new people and build long-lasting relations with your products and services.

=== Factor of safety
This pattern states that the number of safety measures should correspond to the level of uncertainty in the design parameters, and vice versa. If the impact of something going wrong is very small, do not add additional safety and security measures, which only decreases usability.

Small payments in shops should be easy and fast. Large amounts should emphasize safety and security. 

Bitcoin is very well known for being the most secure cryptocurrency network with the support of over a hundred million terra hashes every second to process and validate network transactions into the blockchain. Not even the most powerful supercomputers combined can compete against this. But with a market cap worth in the billions of dollars, it is no surprise that security is a top priority for storing, sending, and receiving value.

=== Feedback loops
Feedback occurs when outputs of a system are routed back as inputs as part of a chain of cause-and-effect that forms a circuit or loop. The system can then be said to feed back into itself. Simple causal reasoning about a feedback system is difficult because the first system influences the second, and the second system affects the first, leading to a circular argument.

Feedback loops work by removing uncertainty and doubt. People who see their actions modify subsequent results are more engaged.

A feedback loop is a cycle in which output feeds back into a system as input, changing subsequent outcomes. Without feedback, people may become insecure and helpless. Feedback loops keep people interacted and engaged in situations in which we see our actions modify future results. Games are perfect examples of continuous actions and reactions. But when tasks feel unimportant or boring, feedback loops may become counterproductive and decreases people’s attention and motivation to complete tasks. Positive mimicry is that we learn by modeling our behavior after others. Tutorials often use feedback loop for demonstrating the use of a product or service. This way, people can simply redo the same steps, as seen in the example. When adding feedback loops, make sure they add value or reduce risk. Also, make them feel instant. If it takes more than 10 seconds, then consider adding an intermediate step to show that something is happening. A simple message or indicator indicating that a transaction has been received but not yet processed is often enough.

Let people quickly onboard your products and services. Positive feedback loops stimulate learning and growth. Feedback loops are essential after the user takes action, such as sending, receiving assets.

=== Flexibility trade-offs
As the flexibility of a design increases, the usability, security, and performance of the design decrease. Related to this is the concept of feature-creep. With software, it is easy to add new features and generalize functionality, but very hard to remove something which is already in there. The problem with this is that more features require more mental strain for users. But also, developers will have a more difficult time managing complexity and keeping the code clean and error-free. Managing complexity is one of the most challenging things to do.

In an ever-demanding world, people expect everything to be possible. Yet, in practice, there are always trade-offs to make. Solutions that function as a jack-of-all-trades are also a master of none. Pleasing everyone simply means that everyone will need to make compromises, and nobody ends up happy. Specialized solutions that excel at just a few core beliefs will always find their target audience. The less you change on these core beliefs; the more people stay as brand evangelists. 

Bitcoin’s approach is to be very strict in adding new features to the code. Much easier is it to add a little bit of flexibility in the base layer, which allows much more flexibility in the layers above it. But most of the changes are focused on optimization regarding increased security, privacy, and transactions.

=== Form follows function
This pattern states that the shape of an object should primarily relate to its intended function or purpose. If not, then often, the interactions and overall experience will suffer from aesthetic compromises.  Although this principle is mostly associated with the architectural design of buildings or industrial product design, it is increasingly used in digital design as well. The effect of this pattern is to create awareness that design should not be confused with art, wherein every form and shape is allowed. Design, on the other hand, is the creation of intent. It has to have a purpose other than itself. If a function is well-executed, it can be both useful as well as beautiful. 

Mobile-first approach. Mobile devices are a standard technology around the world and are the thing that users use every day. Developers are increasingly building solutions for mobiles. App stores have a better set of rules and protocols to clarify what can be done and protect users from scams, mobile devices, and operating systems have better-designed security environments and built-in 2FA (even helped by Fortnite).

The crypto industry has, until now, been a desktop-first industry. It is inconceivable that this remains so when the most used computing devices are mobile. When designing products and services, consider using both the optimal as well as the most practical context. Consumers will most likely use their mobile devices for small payments on-the-go. But more significant amounts are more often a combination between a dedicated hardware-wallet and a desktop application to safely set up, store, and manage funds coming from exchanges. Online companies such as stores and exchanges may use a desktop as well, but physical retailers might be better off with dedicated tablet-sized terminals. Each participant in the network has a preferred method of interaction. 

=== Game theory
Game theory is a branch of applied sciences, and economics that looks at situations where multiple parties make decisions in an attempt to maximize their returns. Systems can be designed in such a way to either stimulate competition between single parties (zero-sum game) or to stimulate cooperation where multiple parties will benefit. 

Game theory can help motivate certain behaviors within a situation. Systems which do not include a substantial benefit on strategic decision making, often lack fewer incentives for parties to participate or take actions. However, people dislike being overly-controlled and losing their freedom of choice. This feeling might lead to people leaving or abandoning the game-theoretical system altogether.

One of the most known collaborative game theory mechanisms in Bitcoin is mining. The system incentivizes miners to run a mining node and compete against other miners. Those who validate transactions, and solve the nonce problem, need to find ways to maximize their returns strategically. As a result, the incentives given to the miners benefit the Bitcoin ecosystem as a whole for having a very secure network. 

=== Gamification
People are more likely to engage in activities in which meaningful achievements give them recognition for their work. Gamification techniques stimulate people's natural desires for socializing, learning, mastery, competition, progress, status, and self-expression. The goal of gamification is helping people achieve some desirable outcomes. But when using gaming elements for the wrong reasons, with false incentives, they are considered a dark pattern.

Early gamification strategies use rewards for players who accomplish desired tasks or competition to engage players. Types of bonuses include points, achievement badges or levels, the filling of a progress bar, or providing the user with virtual currency. Making the rewards for accomplishing tasks visible to other players or providing leader boards are ways of encouraging players to compete.

Bitcoin is full of gamification elements, often created by the community. One such example is the prestigious 1 million club, for holding at least 21 bitcoins. Another example is the creation of vanity-addresses, where people specifically try to include certain words or numbers within their bitcoin address.

=== Humor effect
People enjoy and more easily remember humorous or outrages situations. Only a small percentage of companies add a bit of humor or to their products and services. Yet nearly everybody likes to laugh. When done right, it can boost the likeability of your brand. But get it wrong, and it may hurt the brand perception.

Memes can be particularly supportive during harsher times to lighten up the mood. As a brand, it is good to use humor effect only in the most positive way. Particular forms of humor, such as sarcasm or irony, may not be appreciated by everybody. Sometimes the most exciting and smart jokes are the ones that also contain a message related to a particular task or activity. As a tip, be careful not to put humor into every aspect of the design. Use it sparingly or make people make a little effort to get to the joke. Puzzles and cryptography have often been a good match.

Probably the best examples of humor within the Bitcoin ecosystem are the use of memes. These images, videos, or pieces of text, are typically humorous and spread rapidly by Internet users, often with slight variations of the original material. Memes work very well because they are concise in their message; nearly everyone can create and share often strengthens like-minded communities. 

=== IKEA effect
The IKEA effect comes from the name of Swedish retailer IKEA, which is known for selling unassembled boxed furniture. By putting things together, people feel a sense of accomplishment and fulfillment when they succeed. The items they bought are valued higher by those who put additional energy into building it. This subjective added value by doing things can be applied to many more aspects to drive behavior.  

One way to use this principle is by allowing people to create or modify things within your product or service so that it becomes more personalized and valued by the effort they put into it. Customizing layouts, background, or allowing personal images or texts take little effort, yet have a significant effect on people appreciating the product or service. Another way is allowing people to build and extend products such as wallets or exchanges so that they become valuable for these persons through the work they have done.

Things that people have helped make, whether software or digital assets, they place a level of ownership over. Collaborative tools and services such as GitHub or Fiverr allow people to work on Bitcoin’s products and services. Open marketplaces may help more people work on creating better products as well as promoting their skills and services as professionals.

=== Inclusion
In the past, accessibility was considered when designing products or services for people with disabilities. The scope for inclusion has broadened a lot in the last couple of decades. Nowadays, it has become common practice to embrace accessibility as part of everyday design. Some differences between individuals may be physical of body or place, but inclusion also concerns about the diversity of beliefs, thoughts, and feelings.

Creators who adopt inclusion into their products and services will be able to make a major difference and impact on people’s lives. Designing for inclusion may end up being a key differentiator until this is adopted by every competitor. Not focussing on inclusion may very well negatively affect adoption and retention. But the first step to inclusion is to ignore the way things currently work for us and to try achieving the same things with one handicap at a time. This way, you will find out where the barriers are and how to fix them.

One of the major effects of not considering accessibility is exclusion. And that is the opposite of what Bitcoin stands for. Designing for accessibility is not easy because there are many types of barriers. Some barriers can be physical disabilities, which means a loss or limitation to a physical function that may affect a person’s mobility, dexterity, or stamina. Other barriers can be sensory disabilities, which affect one or more senses like sight, hearing, smell, touch, taste, or spatial awareness. Or mental barriers that are related to skills, knowledge, or proficiencies. And not to forget contextual barriers like laws, regulations, social conventions, access to information, and more. Keep in mind that all kinds of people benefit from well-designed implementations, not just those who need additional help.

=== KISS
The acronym KISS stands for “keep it simple, stupid" or "keep it stupid simple" and was noted as a design principle by the U.S. Navy in 1960. One of the problems today is not the lack of, but the excess of information. When there is too much information to process, it may lead to indecisiveness, more complexity, and an increase in decision time. The KISS principle states that simple designs work better and are more reliable.

The advice is to hide complexity from the end-user. Be careful when adding new features. Consider if these features are core or non-core features that people will use every day. Use the opt-in methodology for non-core features.

For Bitcoin, different levels of simplicity are related to the level of control and self custody people want to have. With each increasing level, more knowledge and experience are required to become in full control. At the top level, it starts with basic Bitcoin knowledge. Since everything is decentralized and no single company owns or controls bitcoin, getting the right information can be challenging. Most likely, the knowledge they received is the information from the media, which isn’t always the closest and most neutral source of information. At the second level are basic interactions such as purchasing, transacting digital assets. Typically exchanges act as a starting point for many new people getting into space. But unlike a physical exchange, everything is digital and online. And sometimes, before people can exchange, they are required to supply the exchange with proof of their identity and residence. It is typically taking some hours or days to complete. Then at the third level starts self-custody, which includes safely and securely creating and managing a wallet with passwords, seeds, keys, and addresses. The fourth level includes mastery, which includes additional steps and measures to enhance privacy and security, such as offline storage and mixing services. The last level is full autonomy and custody by being part of the network and managing transactions on a personal node.

=== Legibility
As humans, we are very dependent on our sight when it comes to digital processing information. Much of the information is presented on a screen. When designers are not optimizing the content for the right context, it makes it unnecessarily difficult to take in and process. Legibility is the visual clarity of text, generally based on size, typeface, contrast, line length, and spacing. But most of the same elements for text apply shapes and forms as well.

When designing highly secured solutions like hashed transactions and private keys, keep in mind that humans prefer patterns which they are familiar with them and easy to read, process, and remember. Good practices are to convert unique strings into human-readable words, splitting large strings into smaller chunks, highlighting certain aspects, and validating or correcting complex information.

In general, they are still dependent on the options and functionality that the network provides. One example is how bitcoin addresses are represented by default; they typically consist of a large string of letters and numbers starting with a 1, 3, or bc1. The latter starting with bc1 is a good example of a new native segwit address, based on the Bech32 standard. Besides the performance benefits (smaller transactions) or financial benefits (lower transaction costs), this standard also includes some usability improvements. The first being that no mistakes on capital letters can be made. For example, the letter O is removed because this looks like the number 0. But also able to correct mistakes, via validations & checksum. Or a fixed-length check incase someone entered too many or too little. But perhaps even more practical solutions come from human-readable addresses. This approach lets people choose a unique domain that they can link to their public address. This way, they can simply remember and give this name (like satoshi.eth or satoshi.crypto) to someone who uses a wallet that supports this kind of blockchain domain names.

=== Literacy
Literacy is traditionally defined by dictionaries as the ability to read and write, although broader interpretations insist that any particular instance of reading and writing is always taking place in a specific context, as the proliferation of concepts like "conventional or basic literacy, functional literacy, digital literacy, media literacy, legal literacy, computer literacy, medical literacy, and information literacy" suggest. The general consensus among researchers that literacy always includes social and cultural elements is reflected by UNESCO's inclusion of numbers, images, digital media, cultural consciousness, and other means of understanding, communicating, gaining useful knowledge, problem-solving, and using the dominant symbol systems of a culture in its definition of literacy. The concept of literacy is expanding across OECD countries to include skills to access knowledge through technology and the ability to assess complex contexts.

More education is needed. On schools, at home, amongst friends, government, and social media.

When considering literacy in Bitcoin, we refer to the ability to understand Bitcoin.

=== Loss aversion
We hate losing or letting go of what we have (even if more could be had). In cognitive psychology and decision theory, loss aversion refers to people's tendency to prefer avoiding losses to acquiring equivalent gains: it is better not to lose $5 than to find $5. The principle is very prominent in the domain of economics. What distinguishes loss aversion from risk aversion is that the utility of a monetary payoff depends on what was previously experienced or was expected to happen. Some studies have suggested that losses are twice as powerful, psychologically, as gains. Loss aversion was first identified by Amos Tversky and Daniel Kahneman. Humans may be hardwired to be loss averse due to asymmetric evolutionary pressure on losses and gains: for an organism operating close to the edge of survival, the loss of a day's food could cause death, whereas the gain of an extra day's food would not cause an extra day of life (unless the food could be easily and effectively stored).

Do not trade, but dollar-cost-average. For spending, use lightning and small amounts.

Loss aversion happens at trading. But it also prevents people from spending bitcoins, because it is considered more precious than fiat currencies.

=== Metaphors
The most powerful approach to learning something new is to tie it to something we or are familiar with or already know. This prior knowledge of how something works is also called a mental model. When people interact with a new object or person, they recall previous experiences and mental models that may be relatable to the new situation. 

When designing new products and services, use familiarity bias and conceptual metaphors so that people will have the right expectations on how it is used.

To help people understand what Bitcoin, it is best to find similar generic models to which people can relate. Unfortunately, in the last decade, some poor mental models have been chosen to explain how people should interact with Bitcoin's products and services. One example is the metaphor used to manage bitcoins. Nearly everyone knows this as a cryptocurrency wallet. And although this is used to send and receive money, it is a common misconception that wallets hold people's funds. This, however, isn't true, but what they do contain are the private and public keys. Therefore perhaps a better metaphor would have been a keychain to gain access to funds stored in the blockchain. Another metaphor often for bitcoin is being digital gold. It helps people frame the concept better and how to use it. But if the future decides to use it in a different way, the metaphor is no longer correct.

=== Modularity
Managing system complexity by dividing large systems into smaller, self-contained systems. Modular design, or "modularity in design," is an approach (design theory and practice) that subdivides a system into smaller parts called modules that can be independently created and then used in different systems. A modular design can be characterized by functional partitioning into discrete scalable, reusable modules; rigorous use of well-defined modular interfaces; and making use of industry standards for interfaces. A modular system with this limited modularity is generally known as a platform system that uses modular components. Examples are Auto platforms or the USB port in CE platforms. In design theory, this is distinct from a modular system which has higher dimensional modularity and degrees of freedom. Modular system design has no distinct lifetime and exhibits flexibility in at least three dimensions. In this respect, modular systems are very rare in markets. Mero architectural systems are the closest example of a modular system in terms of hard products in markets. Weapons platforms, especially in Aerospace, tend to be modular systems, wherein the airframe is designed to be upgraded multiple times during its lifetime, without the purchase of a completely new system. Modularity is best defined by the dimensions affected or the degrees of freedom in form, cost, or operation. Modularity offers benefits such as a reduction in cost (due to less customization), interoperability, shorter learning time, flexibility in design, non-generationally constrained augmentation, or updating (adding new solution by merely plugging in a new module), and exclusion. Modularity in platform systems, offer benefits in returning margins to scale, reduced product development cost, reduced O&M costs, and time to market. Platform systems have enabled the wide use of system design in markets and the ability for product companies to separate the rate of the product cycle from the R&D paths. The biggest drawback of modular systems is the designer or engineer. Most designers are poorly trained in systems analysis, and most engineers are poorly trained in design. The design complexity of a modular system is significantly higher than a platform system and requires experts in design and product strategy during the conception phase of system development. That phase must anticipate the directions and levels of flexibility necessary in the system to deliver the modular benefits. Modular systems could be viewed as more complete or holistic design, whereas platforms systems are more reductionist, limiting modularity to components. Complete or holistic modular design requires a much higher level of design skill and sophistication than the more common platform system.

When creating new open-source products and services on top of Bitcoin, keep in mind that others might want to look or reuse parts of your code as well. Separate your code into functional units that do one thing. This way, it is easier to collaborate or perhaps even replace this functionality with something new.

One of the biggest strengths of Bitcoin is being an open-source project. This allowed everyone to see, download, and adjust the code wherever they wanted. But large and complex projects such as Bitcoin, it needs a logical separation of functionality when multiple people are working on certain parts simultaneously. Looking at the Bitcoin code, developers can work independently on several modules and components. Some of the more recognizable components are the consensus rules, network nodes, scripts.

=== Nudge
A nudge is a way of modifying behavior without restricting options or changing incentives. Nudge is a concept in behavioral science, political theory, and behavioral economics that proposes positive reinforcement and indirect suggestions as to ways to influence the behavior and decision making of groups or individuals. Nudging contrasts with other ways to achieve compliance, such as education, legislation, or enforcement. The nudge concept was popularized in the 2008 book Nudge: Improving Decisions About Health, Wealth, and Happiness, by two American scholars at the University of Chicago: economist Richard Thaler and legal scholar Cass Sunstein. It has influenced British and American politicians. Several nudge units exist around the world at the national level (UK, Germany, Japan, and others) as well as at the international level (e.g., World Bank, UN, and the European Commission). It is disputed whether "nudge theory" is a recent novel development in behavioral science or merely a new term for one of many methods for influencing behavior, investigated in the science of behavior analysis.

A nudge, as we will use the term, is an aspect of the choice architecture that alters people's behavior predictably without forbidding any options or significantly changing their economic incentives. The intervention of nudges must be easy and cheap to avoid. Nudges are not mandates. Putting fruit at eye level counts as a nudge. Banning junk food does not. Add nudges to your products and services where you positively want to help people do the right thing for them or prevent them from making mistakes. When a nudge only serves your interest, refrain from using it, for this can work counter-effective.

The use of nudges is applicable mostly for products and services build on top of the Bitcoin system because that is where most of the interaction happens with people. But when looking at Bitcoin from a holistic view, then any form of communication may include nudges. For some, this may start with the Bitcoin website, social media, or cryptocurrency exchanges. These offer some great opportunities to help people understand why Bitcoin is, in some ways, a better alternative for a currency than fiat money. A nudge could be a reference or link to the Bitcoin whitepaper or to books written about economic models, to gain a better understanding of why.

=== Ownership bias
We more highly value goods or services once we feel like we own them. We also feel more connected to people who share the things we believe in or own. In psychology and behavioral economics, the endowment effect (also known as divestiture aversion and related to the mere ownership effect in social psychology) is the finding that people are more likely to retain an object they own than acquire that same object when they do not own it. This is typically illustrated in two ways. In a valuation paradigm, people's maximum willingness to pay (WTP) to acquire an object is typically lower than the least amount they are willing to accept (WTA) to give up that same object when they own it—even when there is no cause for attachment, or even if the item was only obtained minutes ago. In an exchange paradigm, people given a good are reluctant to trade it for another good of similar value. For example, participants were first given a Swiss chocolate bar were generally unwilling to trade it for a coffee mug, whereas participants were first given the coffee mug were generally unwilling to trade it for the chocolate bar. A more controversial third paradigm used to elicit the endowment effect is the mere ownership paradigm, primarily used in experiments in psychology, marketing, and organizational behavior. In this paradigm, people who are randomly assigned to receive a good ("owners") evaluate it more positively than people who are not randomly assigned to receive the good ("controls"). The distinction between this paradigm and the first two is that it is not incentive-compatible. In other words, participants are not explicitly incentivized to reveal the extent to which they truly like or value the good. The endowment effect can be equated to the behavioral model Willingness to Accept or Pay (WTAP), a formula sometimes used to find out how much a consumer or person is willing to put up with or lose for different outcomes.

Although ownership bias can lead to creating healthy communities and brand-loyalty, there are also darker sides to keep in mind. Taking a negative approach could lead to diversity and toxic tribalism. It is important to invest, especially in the things which we share with others and respect the differences we have.

Bitcoin is all about sovereignty and ownership of digital assets through private keys. Andreas Antonopoulos also has a famous quote about this saying; “Your keys, your bitcoin. Not your keys, not your bitcoin.”. This is a common warning to new people who leave their bitcoins at third-parties like exchanges or custody funds. When these get hacked or someone who does have access, decides to go AWOL, then this often leads to loss of funds without any means of getting their funds back. Creating awareness for ownership bias is good. Proof of Keys is an example of a yearly event on January 3rd, to everyone to withdraw their funds from exchanges into wallets of which they own their private keys. By doing so, people are also made aware that they are responsible for safekeeping the assets they control and own. This makes people more emotionally invested in the things they own. Endowment effect: We overvalue things that we own, regardless of their objective market value. This is illustrated simply in two examples: people become reluctant to part with goods they own for their cash equivalent and when people are willing to pay less for a good than they are willing to accept when selling it. The endowment effect is an illustration of status quo bias and can be explained with loss aversion and prospect theory. Simply by owning a cryptocurrency, you value it more than you would otherwise. In traditional finance, traders have been known to stick with assets they own even if they become unprofitable simply because of their emotional attachment to them.

=== Paradox of choice
Having an excessive amount of options in a particular decision can lead to worse outcomes. Choice overload can lead you to question the decisions you make before you even make them, set you up for unrealistically high expectations, and make you blame yourself for any failures. As people, we love to choose from options. And for certain things, this is true. But when it comes to decision-making, studies have shown that we are less likely to make a choice when the number of options increases. We cannot decide and have the urge to postpone. This is also related to another research theory called Hick’s law. Hick's law, or the Hick–Hyman law, named after British and American psychologists William Edmund Hick and Ray Hyman, describes the time it takes for a person to decide as a result of the possible choices he or she has: increasing the number of choices will increase the decision time logarithmically. 

The general rule is to keep things simple and support shortcuts with a minimum amount of steps or time. Sequencing is an approach that is often used in these cases. We are more likely to take action when complex activities are broken down into smaller tasks. This does not always imply that all steps need to be taken at the same moment. Sometimes a gentle reminder, later on, to finish certain steps is a good option as well.

Giving users too many choices for goods and services to exchange for a utility token may lead them to a bad choice. Technological innovation doesn’t stop, and neither does Bitcoin. While moving forward, Bitcoin also holds one foot in the past as it strives always to be backward compatible. This means that whatever was possible in the past, should also be possible in the future. The drawback is that this creates an endless supply of options. Let’s take the creation of a wallet, for example. This is by far the most common exercise when sending and receiving bitcoins. However, in most cases, the beginning user is immediately confronted with the type of wallet they want to create; Legacy, SegWit (P2SH), or HD SegWit (BIP84 Bech32 native). For those who are just starting, this is too many options and too advanced options, and some may choose to exit.

=== Peak-end rule
We judge our past experiences almost entirely by their peaks (pleasant or unpleasant) and how they ended. The peak-end rule is a psychological heuristic in which people judge an experience largely based on how they felt at its peak (i.e., its most intense point) and its end, rather than based on the total sum or average of every moment of the experience. The effect occurs regardless of whether the experience is pleasant or unpleasant. According to the heuristic, other information aside from that of the peak and end of the experience is not lost, but it is not used. This includes net pleasantness or unpleasantness and how long the experience lasted. A peak-end rule is thereby a specific form of the more general extension neglect and duration neglect.

When creating products and services, ask yourself which moment do you want people to remember. Especially the beginning and the end of interaction between your customer and your product are moments that will be most remembered. Moments such as sending and receiving digital assets are great for bringing a smile to people’s faces. Or if this style does not suit your audience, think about what they do want to remember. Perhaps you should focus on reassuring people and keeping them updated along every step of the process after sending a transaction. 

Within Bitcoin, there are many opportunities for including peak-end rules, yet they are scarcely implemented. Luckily many brands are successfully using this technique to optimize their customer journey by ending on a high note. Even banking apps are not shy of using this pattern to delight people with funny quotes or animations after they successfully paid payment requests from friends or family.

=== Privacy
Privacy is the ability of an individual or group to seclude themselves or information about themselves and thereby express themselves selectively. The boundaries and content of what is considered private differ among cultures and individuals. When something is private to a person, it usually means that something is inherently special or sensitive to them. The domain of privacy partially overlaps with security, which can include the concepts of appropriate use, as well as protection of information. Although the level of privacy protection law differs from country to country, it is advisable to adopt privacy by design by default.

Within Bitcoin, the community needs to think hard about which path to take in the future. Since Bitcoin not restricted to borders or laws, the community decides which approach is best for those who would like to make use of Bitcoin. Both transparency, as well as privacy, have their benefits. Several projects, such as Monero and Grim, have their privacy protection mechanisms. But they also allow the user to choose if they would publicly share parts of information with others.

Bitcoin from the beginning includes a high-level of privacy by hiding the identity behind anonymous private keys and addresses. However, when someone’s identity can be linked to a certain address, a lot of information becomes exposed through the traceability of transactions on the blockchain. Full privacy is not yet implemented, and many initiatives are currently being explored and tested.

=== Readability
The ease with which text can be understood, based on the complexity of words and sentences. In natural language, the readability of text depends on its content (the complexity of its vocabulary and syntax) and its presentation (such as typographic aspects like font size, line height, and line length). The goal of higher readability is to ease the reading effort and speed for any reader, but it is especially important for those who do not have high reading comprehension. In readers with average or poor reading comprehension, raising the readability level of a text from mediocre to good can make the difference between success and failure of its communication goals.

When designing products and services, be very clear who your target audience is and adjust your vocabulary accordingly. The second part is about keeping the information as simple, short, unique, and relatable as possible. Be mindful of every word you put into your product or service. But allow people to take a sidestep if they would like to know more about a certain topic.

Readability within Bitcoin is still a big issue for newcomers. Almost immediately, they are faced with technical terminology, which is very helpful for developers, but counterproductive to people simply using it. The concept of “balance” within a bitcoin wallet, is a good example which is helpful for people because this relates to something they already know. However, under the hood, what a user sees as the balance is a collection of unspent transaction outputs. 

=== Recognition over recall
It is easier to recognize things we have previously experienced than it is to recall them from memory. Many situations nowadays require us to recall information such as passwords or codes, each different from each other. Yet all of these adds up to the mental and physical effort required to complete a task. There are two types of performance load; cognitive and kinematic. Cognitive is the mental effort, and the kinematic load is physical steps.

Different circumstances require different solutions. However, whenever possible, allow people to recognize solutions based on recognition rather than recall the entire piece of information. Support suggestions such as the format of the information or auto-complete words from fixed lists such as seed phrases. And because people are mostly visually oriented people, sometimes recognizing images work better than recognizing words, yet the level of security remains the same.

Although the Bitcoin system heavily relies on the use of private key cryptography, it is not doable to remember long hashes of information. Instead, they are stored inside wallet applications, which by default, require a passphrase or number to access. There are brain wallets that refer to the concept of memorizing a seed phrase, which can be used to access funds on the blockchain indirectly. However, if a brain wallet is forgotten or the person dies or is permanently incapacitated, access is lost forever. Regardless if people remember their seed or not, the fact that words can be used to restore public and private keys is an improvement from a human perspective.

=== Reinforcement
The term reinforce means to strengthen and is used in psychology to refer to anything stimulus which strengthens or increases the probability of a specific response. In behavioral psychology, reinforcement is a consequence applied that will strengthen an organism's future behavior whenever that behavior is preceded by a specific antecedent stimulus. This strengthening effect may be measured as a higher frequency of behavior (e.g., pulling a lever more frequently), longer duration (e.g., pulling a lever for longer periods of time), greater magnitude (e.g., pulling a lever with greater force), or shorter latency (e.g., pulling a lever more quickly following the antecedent stimulus). 

There are four types of reinforcement: positive, negative, punishment, and extinction. We’ll discuss each of these and give examples. Positive Reinforcement - the examples above describe what is referred to as positive reinforcement. Think of it as adding something in order to increase a response. For example, adding a treat will increase the response of sitting; adding praise will increase the chances of your child cleaning his or her room. The most common types of positive reinforcement or praise and rewards, and most of us have experienced this as both the giver and receiver. Negative Reinforcement - think of negative reinforcement as taking something negative away in order to increase a response. Imagine a teenager who is nagged by his mother to take out the garbage week after week. After complaining to his friends about the nagging, he finally one day performs the task, and to his amazement, the nagging stops. The elimination of this negative stimulus is reinforcing and will likely increase the chances that he will take out the garbage next week. Punishment - punishment refers to adding something aversive in order to decrease a behavior. The most common example of this is disciplining (e.g., spanking) a child for misbehaving. The reason we do this is that the child begins to associate being punished with negative behavior. The punishment is not liked, and therefore to avoid it, he or she will stop behaving in that manner. Extinction - when you remove something in order to decrease a behavior, this is called extinction. You are taking something away so that a response is decreased.

Research has found positive reinforcement is the most powerful of any of these. Adding a positive to increase a response not only works better but allows both parties to focus on the positive aspects of the situation. Punishment, when applied immediately following the negative behavior, can be effective, but results in extinction when it is not applied consistently. Punishment can also invoke other negative responses, such as anger and resentment. A good example of positive reinforcement is rewarding people with cryptocurrencies after learning about them, what problem they solve, and how to use them. Another example is reminding people to store or backup their private key or seed phrases. Some people may find these reminders annoying, but they are rewarded for doing something they will benefit from later on. 

=== Reputation
We care more deeply about personal behaviors when they may affect how peers or the public perceive us. In online social contexts, sharing actions with others helps encourage good conduct. People build a reputation through things like sharing information, connecting people, and keeping a record of their activities. And through our interactions, we assess if they either enhance or diminish our standings relative to others and our personal best.

Building a good reputation takes time and hard work. Yet when you abuse your reputation and lose trust, the negative effects occur in the blink of an eye. But good reputable people may act as examples to new people willing to enter the space and seeking for information and guidance. With all the distrust and scams that happen on the internet, finding people with a good reputation is difficult. More people are needed to help others by taking the time and teaching them to become self-sovereign in this space, and hopefully becoming trustworthy and reputable people themselves.

When creating a new solution like Bitcoin, focussing on the technology is not enough. Although incentivized, people did not know for sure if this internet money was going to fly. Back then, using Bitcoin was much harder than it is today, and there were nearly no instructions, videos, or exchange support. The only thing people had was each other chatting on forums, via email and IRC channels. You often had to trust someone on the other side, to exchange bitcoins for dollars, which could take days or weeks to process. Eventually, out of those interactions and conversations with other people, trust and reputation were earned. And build on this intangible reputation, others would follow, and the Bitcoin community would grow to the millions today. 

=== Scarcity
We infer value into something that has limited availability or is promoted as being scarce. Things become more desirable when they are in short supply or occur infrequently. Given a choice between action and inaction, a limited time/duration to respond increases the likelihood that people will participate. 

Scarcity focusses on limited resources such as time, energy, art, exclusivity. The harder it is to obtain, the desirable something becomes. Scarcity in design can help create focus and awareness on what is considered valuable and what is not. Something which cannot be bought is time. Every person has only a limited amount of it. Therefore in creating solutions, be careful not to waste this valuable asset with poor designs that hinder people from reaching their goals. 

There have been many forms of money in history, but in some ways, bitcoin works better as sound money than others because, in the open bitcoin market, there will never be more than 21 million bitcoins ever in existence. Another characteristic of bitcoin is the deflationary production rate of newly minted bitcoins, which will be cut in half, approximately every four years (210,000 blocks). Unlike any other asset, this cannot be changed and makes it easy to predict. Especially bitcoin-miners like this fact because they can build their business around this certainty.

One of the key features of bitcoin is being a scarce asset. Unlike any other fiat currency, no more than 21 million bitcoins can ever be created. Combine this with a deflationary supply, where the supply of new bitcoins is halved nearly every four years, and you end up with a difficult to get asset over time. For some, obtaining one single bitcoin and thus to belong to the 21 million-club, is perceived as very desirable. We naturally desire things that are perceived as exclusive or belonging to a select few. 

=== Seamlessness 
Seamlessness in design is about the ease of switching between one product or service to another. Or when switching from one device to another. Often this occurs when the functionality of one product or service stops, and another continues. 

When creating a product or service, look beyond your solution. Consider the whole end-to-end customer journey to map which other products and services people may be used in combination with your own. Then adapt your solution accordingly to either receive (import) information from other apps or send (export) information to other applications. When creating seamless services, do not take the ‘zero-sum game’ approach, where third party solutions are considered competitors. Instead, imagine that people love your product, but use it in conjunction with other functions that you may not have heard about or be offering. For example, people using your wallet in combination with a third party bookkeeping program for filing tax.

Bitcoin, in a way, acts as a platform for many applications and services which are built on top of it. One example in which devices interact with each other is by sharing QR-codes, which contains information such as private keys or wallet addresses.

=== Security
Security nowadays needs no introduction. Security by design has been the default for nearly every professional developer when it comes to the protection and processing of data. With our world becoming ever more digital and dependent on digital technologies, things can go seriously wrong when certain data is being misused or manipulated. The impact of security breaches is extremely high for both individuals as for nations as a whole.

From a technical perspective, there are a lot of cool privacy and security related features being created for Bitcoin. Yet it is easily overlooked that the biggest security risks are not quantum computers, but simple human mistakes. The greatest risk for security is complexity. When creating new security measures, it is good to keep in mind that humans with all of their capabilities, but also their disabilities need to use Bitcoin. Increasing security also implies making it easier and not harder for people to use. Decide which security measures are mandatory and which ones are offered optionally. The level of usability should be according to the proficiency and experience of the user. And the level of security should be proportional to the value. The Bech32 standard is an example wherein several safety checks are included to help a user recover from entering mistakes.

Security has been one of Bitcoin’s greatest achievements. With a dozen mining farms competing for 24/7 for a block reward and securing a ledger from malicious transactions. But do not forget the strong cryptographic hash functions which are used for data encryption.

=== Self-expression
People seek opportunities to express their personalities, feelings, or ideas. How we share and express ourselves to others forms the basis of our personality, as understood by everyone but us, and sets the tone for our entire lives.

When taking a look at all the products and services to build on top of Bitcoin, the possibilities of expressing oneself are endless. On the blockchain, everything of value can be an asset. And ownership of data is controlled by whoever controls the private keys. This means that sharing and removing data based on a self-sovereign identity is much easier than asking a company to remove all personal related data. Or the opposite, centralized entities find it harder to prevent people from expressing themselves on decentralized systems like Bitcoin.

Within Bitcoin, self-expression is tightly related to self-sovereign identity. Behind every address and key, some people use the Bitcoin system as a way to share value. Where they spend it on is up to them. Bitcoin by itself is censorship-resistant and allows people to choose; however, they want to use it. In this sense, bitcoin is a way of expression and communication.

=== Sensory appeal
We are engaged by and more likely to recall things that appeal to multiple senses. 

Where Bitcoin may be disappearing into the background, on the edges, there is much to be gained. After all, people will bring their mental models of how things build on top of Bitcoin's works. Depending on what type of device people are using, more or fewer options are available. A modern smartphone app has multiple input and output possibilities which can be used when using bitcoin as a currency. As a designer, consider integrating additional cues besides visual information on a screen. Perhaps vibrate, flashlight, or play a sound when a transaction is sent or received — this way, people don’t need to keep an eye on their phones all the time.

The Bitcoin network is probably the least expected place to apply sensory appeal. Eventually, Bitcoin should, like the Internet, be omnipresent but invisible and disappeared into the background. The interactions we now see with the network are often the results of poor user-experiences.

=== Serial position effect
The serial position effect is the tendency of a person to recall the first and last items in a series best, and the middle items worst. The term was coined by Hermann Ebbinghaus through studies he performed on himself and referred to the finding that recalls accuracy varies as a function of an item's position within a study list. When asked to recall a list of items in any order (free recall), people tend to begin recall with the end of the list, recalling those items best (the recency effect). Among earlier list items, the first few items are recalled more frequently than the middle items (the primacy effect).

In the ideal situation, most people should not have to see and use this kind of complex information. Either they are hidden or replaced by human-readable substitutes such as unique domain addresses for all types of bitcoin addresses. In cases where this is not possible, using serial positioning can help reduce cognitive load for people. A technique called chunking helps splitting up large pieces of information, like a hash, into several smaller pieces, often separated with a whitespace character. This way, people often look at the first and last pieces to faster recognize, compare, or validate the information.

Those who are familiar with sending and receiving bitcoin transactions know that the Bitcoin system is heavily based on cryptography. To users, this manifests itself by large, complex, and seemingly random strings (which they are not). These strings are everywhere, such as private keys, bitcoin addresses, and transaction hashes.

=== Set completion
The closer a collection is to be complete, the more we desire to collect all pieces. People like to see the whole image completed and dislike incomplete sets. Where there is interest, people like to amass units that add to or complete a set. 

When creating sets or rewards, be sure that they add value to the user. Meaningless rewards are not motivating enough to keep people interested. Also, consider the condition under which rewards are received. When people mined bitcoins on their laptops, they held less value then compared the bitcoins, which are mined with dedicated ASIC miners because it is much harder now, then it was in the beginning. 

In Bitcoin, the scarcest assets are the 21 million bitcoins. In all reality, this is a set that nobody can fully complete. Yet many people strive to possess at least one single bitcoin. However, bitcoin is just one application on top of the Bitcoin network. When creating colored coins, new sets representing any digital asset can be created. Another standard known as ERC721 seems to be getting more traction for creating unique, non-fungible tokens. These tokens can represent anything of a limited edition, such as digital clothing or virtual land ownership.

=== Standardization
Create standards so that others can adopt them and work seamlessly together. The more people and products follow a certain standard, the more it benefits the ecosystem. Producers benefit from standardization in a way that may reduce the cost of not reinventing the wheel. Consumers also benefit from standardization because it allows them to recall and apply previous experiences to something new. 

A standard is often agreed upon by multiple parties when a certain implementation has proven to work well between the producers. They try to find a balance and agree upon the quality, cost, and flexibility. However, in the end, it is up to the consumer to choose which standard works best for them. 

Bitcoin and other cryptocurrencies are continuously experimenting with new and different solutions for different problems. The cryptocurrency Monero, for example, has a different standard to mnemonic seeds, compared to Bitcoin's BIP39 standard, which includes The English-language wordlist of 2048 words. From a consumer perspective, one single standard for all managing different blockchains within one wallet would be much appreciated. 

=== Status quo
The status quo states that people tend not to change their behaviors unless they are incentivized. This implies that adopting complex technologies like Bitcoin can take a long time before being used. Global changes and adoption happen slowly for good reasons. If everything in the world were in constant flux, humanization would collapse. One could argue that this is already happening due to accelerators like the Internet. 

When designing something new, it is good to keep in mind the reasons why people should come into action and show the benefits for their effort or mention the drawbacks if they do not. To help people on board more easily, consider using an easy onramp from one system to another. And allow the option to switch back if they have a change of heart.

Bitcoin so far has also challenged the status quo quite a bit. For those in need of something radically different, challenging the current systems is a good thing. But those who do not see any benefits, are inclined to keep things as they are. 

=== Storytelling
Telling and sharing stories is as old as human civilization. Good, vivid, and compelling stories bind people together, informs, or entertains people. Storytelling is a technique often used to add flavor to cut and dry information. It also brings structure, narrative, context, and emotion to the mix, which is often lost in bullet points. When creating a story, people are better at visualizing the information which they are being told. Also, it aids in better recalling information over time.

Short stories can be very helpful when teaching people new things. The bitcoin story is one example, but there are no limits to what a story should be. Typically, every piece of interaction between people and a part of the Bitcoin ecosystem can be eligible for a good story. 

The creation of Bitcoin by itself has all the ingredients of a great story. But the media and politics seem to create negative twists around it. Instead, Bitcoin needs more promotional material highlighting the uniqueness and origin stories that deeply hit common people on an emotional level. For this, it is good to look beyond swag, such as t-shirts, but take an example on commercial companies and how they are advertising their brand story. Bitcoin’s ecosystem needs more knowledge from marketers to strongly put down an attractive and lovable brand that is unique and of the highest quality.

=== Value attribution
Value attribution describes our tendency to imbue people or objects with certain qualities based on perceived value, rather than on objective data. We value things when they cost more. Where this undercurrent gets dangerous is in ongoing engagements. Once we attribute a certain value to something, it dramatically alters our perception of subsequent information. Not only that, it affects us even when the value is assigned completely arbitrarily. So once we have attributed value to something, it is very difficult to view it in any other light. And this has the power to derail objective, professional judgment. 

The best strategy to employ here is to be mindful and observe things for what they are, not what they appear to be. Accept that initial impressions could be wrong. Price-models such as stock-to-flow are interesting, but the value of Bitcoin is much more than that, depending on the geopolitical needs of people searching for a solution. When assessing bitcoin's value, consider including the context of why people use it. For some, it may be speculation on scarcity & stock-to-flow. Others may find value in portability, sovereignty, accessibility, privacy, or programmable money. Price follows value.

Once the price reaches new all-time highs, the more coverage it gets from news and media. Also, more people will believe bitcoin is a good investment. Yet the market price and Bitcoin’s more objective fundamentals might be two different things. Dr. Julian Hosp, the author of Blockchain 2.0, once said, “every price will eventually come down to its value.” With this, he referred that price and value are related, but two different things. An anonymous Dutch financial expert under the pseudonym ‘Plan₿,’ introduced a stock-to-flow model for bitcoin. In this model, he found a high correlation between price and scarcity — nearly every bitcoin-halving causing a decrease in supply and an increase in price valuation.
