[preface]
== Preface
By the end of 2017, nearly every media channel was covering bitcoin and other cryptocurrencies. For a brief moment, it was the most-searched-for word on the Internet. Even governments had to look into this phenomenon and create an opinion about it. But it would not take long before that feeling of excitement and attention would soon be over. Market prices crumbled, media attention started to fade away, and many cryptocurrency startups disappeared from the scene.

It was during this period that I wanted to obtain a deeper comprehension of this Bitcoin (r)evolution and understand why it excited so many people. Many hours of videos, books, and conversations followed. But it wasn't until one specific video of Andreas Antonopoulos that changed everything for me. In this video, Andreas presented a talk about Bitcoin with people from a reputable design studio called IDEO. And in that talk, he spoke about some of the "design" flaws of Bitcoin. For a moment, I was dumbstruck. How could this be? One of the most respected proponents and advocates of Bitcoin was talking trash about the technology that he loved so much. What I did not know was that Andreas was setting the stage. At that moment, he intended to challenge the audience of designers to come up with better solutions for Bitcoin so that everyone in the world could use and understand this new technology.

It was at that moment after this video that I had found my mission. With a background in both development and design, I knew that Andreas was right. The next significant challenges would not be faster or more secure blockchains, but to explain Bitcoin as simple as possible, and to as many people as possible.

So with this book, I take you along to view Bitcoin's technology from a (user experience) design perspective. By doing so, I hope that developers, writers, designers, and crypto enthusiasts can create better solutions that are usable for everyone. And although this book mainly focusses on the Bitcoin ecosystem, many of the topics within this book are also applicable to other crypto assets. 
